### ISSUE TITLE
Position-dependent lexing c. 2048

### ISSUE THREAD

**Issue by thomp** [outergod/graylex#1]
The test files at http://db.tt/942RGjP each contain roughly the same content except that the length of the first line varies between the files. I expect line 3 (the line containing '2. X') in each of the test files to be parsed in the same manner irrespective of the relative position of line 3 in the document. However, the manner in which the line is lexed (with the test lexer below) seems to depend on the position of the line relative to the 2048 byte point in the stream. The various test files illustrate the behavior. If line 3 is at positions...

2044-2047 -> parsed as :LIST (2011-05-14C.txt)
2045-2048 -> parsed as :NONEMPTY (2011-05-14D.txt)
2046-2049 -> parsed as :NONEMPTY (2011-05-14E.txt)
2047-2050 -> parsed as :NONEMPTY (2011-05-14F.txt)
2048-2051 -> parsed as :NONEMPTY (2011-05-14G.txt)
2049-2052 -> parsed as :LIST (2011-05-14H.txt)

```
(with-open-file 
 (s "/path/to/bugs/graylex/2011-05-14C.txt") 
 (let ((lexer (make-instance 'graylex:lexer-input-stream 
             :stream s 
             :rules '(("\\d\\. \\S*.*?\\n|$" :LIST)
                  (".*?\\S.*?(\\n|$)" :NONEMPTY)
                  ("[\\t\\r\\f ]*(\\n|$)" :EMPTY) 
                  ))))
   (do* ((token (multiple-value-list (graylex:stream-read-token lexer))
        (multiple-value-list (graylex:stream-read-token lexer))))
   ((null (car token)))
 (format t "-> ~S~%" token))))
```

Apologies if I'm missing something conceptually and this is the expected behavior. Thanks for making graylex available,
- Alan

**Comment by thomp** [comment]
Should have noted that I see the same pattern with SBCL 1.0.39, SBCL 1.0.48, and with ECL from CVS.

**Comment by outergod** [comment]
Hi Alan,

thank you for reporting this issue. It is completely valid and rather a missing functionality in graylex: Tokens that match only in part because the theoretical match is spread across read and unread input. So far, these cases are covered by fetching more content if a match consumes all remaining input, in your case however the incomplete match in the double buffer (which is 1024b by default btw) is not detected as such and the rule skipped. The issue becomes much clearer by comparing these outputs:

```
(mapc #'(lambda (rule)
          (with-input-from-string (stream "abcd")
            (let ((lexer (make-instance 'graylex:lexer-input-stream :stream stream
                                        :rules `(,rule
                                                 ("." :fail))
                                        :buffer-size 3)))
              (do* ((token (multiple-value-list (graylex:stream-read-token lexer))
                           (multiple-value-list (graylex:stream-read-token lexer))))
                   ((null (car token)))
                (format t "-> ~S~%" token)))))
      '(("[abcd]{2}" :win) ("[abcd]{1,2}" :win)))

-> ((:WIN) "ab")
-> ((:FAIL) "c")
-> ((:FAIL) "d")
-> ((:WIN) "ab")
-> ((:WIN) "cd")
```

The one-to-two matches specifier works around the aforementioned problem by making the regexp always consume incomplete matches as well so another round of matching is performed.

Fixing this issue means to find out whether the regexp engine (cl-ppcre in this case) tried to consume all of the input string in case of a failing match in order to trigger a double buffer flush. I'll integrate the failing test case and try to fix the issue ASAP.

**Comment by outergod** [comment]
Should be fixed in 846298a7aebcc1e74f394b8820a60dc1667b94ae
Alan, would you be so kind to verify the fix works for you?

**Comment by thomp** [comment]
Works great with my test cases and in a couple of other contexts now...Thanks.

**Comment by outergod** [comment]
Not a big deal at all, I was to close the issue after your confirmation anyway :) Thank you for using graylex!
